## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
import random 

array = [random.randint(3,8) for _ in range(10)]
changed_array = [-x if 3 < x < 8 else x for x in array]
print('Измененный массив будет иметь следующий вид:')
print (changed_array)

Измененный массив будет иметь следующий вид:
[-5, 8, 3, 3, 3, -4, 3, -4, -4, -6]


**2.** Заменить максимальный элемент случайного массива на 0

In [8]:
array = [random.randint(-100, 100) for _ in range(10)]
max_element = array.index(max(array))
array[max_element] = 0
print(f'индекс максимального элемента в массиве {max_element}')
print(array)

индекс максимального элемента в массиве 9
[46, -15, 20, -78, -61, 3, -57, -37, -30, 0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
from itertools import product

array = [[2,30,7], [9, 100, -80], [89, 20, 456]]
multiplication_array = list(product(*array))

print('Прямое произведение массивов выглядит:')

for i in multiplication_array:
    print(i)

Прямое произведение массивов выглядит:
(2, 9, 89)
(2, 9, 20)
(2, 9, 456)
(2, 100, 89)
(2, 100, 20)
(2, 100, 456)
(2, -80, 89)
(2, -80, 20)
(2, -80, 456)
(30, 9, 89)
(30, 9, 20)
(30, 9, 456)
(30, 100, 89)
(30, 100, 20)
(30, 100, 456)
(30, -80, 89)
(30, -80, 20)
(30, -80, 456)
(7, 9, 89)
(7, 9, 20)
(7, 9, 456)
(7, 100, 89)
(7, 100, 20)
(7, 100, 456)
(7, -80, 89)
(7, -80, 20)
(7, -80, 456)


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
A = [[1, 10, 7],
 [2, 3, 3],
 [8, 6, 7],
 [4, 5, 0],
 [6, 2, 8],
 [9, 3, 0],
 [6, 6, 5],
 [6, 1, 10],]

B = np.array([[2, 3], [4, 5]])

def find_matching_rows(A,B):
    matching_rows = []
    for row_A in A:
        for row_B in B:
            if all(elements in row_A for elements in row_B):
                matching_rows.append(row_A)
                break
    return matching_rows

matching_rows = find_matching_rows(A, B)
print('Все строки в A, которые содержат элементв из каждой строки в B:')
print(matching_rows)

Все строки в A, которые содержат элементв из каждой строки в B:
[[2, 3, 3], [4, 5, 0]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [8]:
matrix = [
 [1, 10, 7],
 [3, 3, 3],
 [8, 6, 7],
 [4, 0, 0],
 [6, 2, 8],
 [9, 3, 0],
 [0, 0, 0],
 [6, 6, 5],
 [6, 1, 10],
 [2, 2, 2]
]

filtered_matrix = np.array([row for row in matrix if len(np.unique(row)) > 1])
print('Строки из неравных значений:')
print(filtered_matrix)

Строки из неравных значений:
[[ 1 10  7]
 [ 8  6  7]
 [ 4  0  0]
 [ 6  2  8]
 [ 9  3  0]
 [ 6  6  5]
 [ 6  1 10]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [17]:
matrix = [
 [0, 0, 0],
 [3, 3, 3],
 [8, 6, 7],
 [4, 0, 0],
 [6, 2, 8],
 [9, 3, 0],
 [0, 0, 0],
 [6, 6, 5],
 [6, 1, 10],
 [2, 2, 2]
]

uniq = np.unique(matrix, axis=0)
print('После удаления строк:')
print(uniq)

После удаления строк:
[[ 0  0  0]
 [ 2  2  2]
 [ 3  3  3]
 [ 4  0  0]
 [ 6  1 10]
 [ 6  2  8]
 [ 6  6  5]
 [ 8  6  7]
 [ 9  3  0]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [14]:
# без использования numpy

x = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

multiplication = 1

for i in range(min(len(x), len(x[0]))):
    diagonal_element = x[i][i]
    if diagonal_element != 0:
        multiplication*= diagonal_element
        
print(f'Произведение ненулевых элементов на диагонали прямоугольной матрицы равняется {multiplication}')

Произведение ненулевых элементов на диагонали прямоугольной матрицы равняется 3


In [15]:
# с использованием numpy

X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
             
diagonal = np.diagonal(X)

non_zero_diagonal = diagonal[diagonal != 0]

product = np.prod(non_zero_diagonal)

print(f'Произведение ненулевых элементов на диагонали прямоугольной матрицы равняется {product}')

Произведение ненулевых элементов на диагонали прямоугольной матрицы равняется 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [14]:
# без использования numpy 

from collections import Counter

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

x_counter = Counter(x)
y_counter = Counter(y)

if x_counter == y_counter:
    print('Вектора задают мультимножества')
else:
    print('Ветора не задают мультимножество')

Вектора задают мультимножества


In [21]:
# с использование numpy 

x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

def multisets(x, y):
    x_sorted = np.sort(x)
    y_sorted = np.sort(y)
    return np.array_equal(x_sorted, y_sorted)

result = multisets(x,y)

if result:
    print('Вектора задают мультимножества')
else:
    print('Ветора не задают мультимножество')


Вектора задают мультимножества


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [12]:
# с использованием numpy 

x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

max_value = None

for i in range(1, len(x)):
    if x[i-1] == 0:
        if max_value is None or x[i] > max_value:
            max_value = x[i]

print(f' Максимальный элемент в векторе среди элементов {max_value}')

 Максимальный элемент в векторе среди элементов 5


In [36]:
# c использованием numpy

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
indices = np.where(np.roll(x, 1) == 0)[0]
values = x[indices]
max_value = np.max(values)

print(f' Максимальный элемент в векторе среди элементов {max_value}')


 Максимальный элемент в векторе среди элементов 6


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [38]:
# без использованием numpy

def run_length_encoding(x):

    values = []
    counts = []

    current_value = x[0]
    current_count = 1

    for i in range(1, len(x)):
        if x[i] == current_value:  
            current_count += 1
        else: 
            values.append(current_value)
            counts.append(current_count)
            current_value = x[i]
            current_count = 1

    values.append(current_value)
    counts.append(current_count)

    return np.array(values), np.array(counts)

x = np.array([2, 2, 2, 3, 3, 3, 5])
values, counts = run_length_encoding(x)

print(np.array(values))  
print(np.array(counts)) 


[2 3 5]
[3 3 1]


In [41]:
# с использованием numpy

def run_length_encoding(x):
    diffs = np.diff(x) != 0 
    indices = np.insert(diffs, 0, True) 

    values = x[indices] 
    counts = np.diff(np.concatenate(([0], np.where(indices)[0], [len(x)]))) 

    return values, counts

x = np.array([2, 2, 2, 3, 3, 3, 5])
run_length_encoding(x)

[False False  True False False  True]


(array([2, 3, 5]), array([0, 3, 3, 1]))

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
from scipy.spatial import distance
import time

X = np.array([[1, 2], [3, 4], [5, 6]])  # 3 объекта из X
Y = np.array([[7, 8], [9, 10], [4,7]])

# использование функции scipy.spatial.distance.cdist

dist_matrix_scipy = distance.cdist(X, Y, 'euclidean')
print('"Матрица евклидовых расстояний с использованием scipy.spatial.distance.cdist :"')
print(dist_matrix_scipy)


# без использование функции 

def euclidean_distance_matrix(X, Y):
    diff = X[:, np.newaxis, :] - Y[np.newaxis, :, :]
    dist_matrix = np.sqrt(np.sum(diff ** 2, axis=-1))
    return dist_matrix

dist_matrix = euclidean_distance_matrix(X, Y)
print("Матрица евклидовых расстояний без использования специальной функции:")
print(dist_matrix)

# измеряем время c помощью встроенной функции 
start_time = time.time()
dist_matrix_1 = distance.cdist(X, Y, 'euclidean')
end_time = time.time()
method_1_time = end_time - start_time

# измеряем время функции euclidean_distance_matrix
start_time = time.time()
dist_matrix_2 = euclidean_distance_matrix(X, Y)
end_time = time.time()
method_2_time = end_time - start_time

diffrence_time = method_1_time - method_2_time

if diffrence_time > 0 :
    print('функцией scipy.spatial.distance.cdist по скорости работы быстрее')
else:
    print('функцией scipy.spatial.distance.cdist по скорости работы медленние')


"Матрица евклидовых расстояний с использованием scipy.spatial.distance.cdist :"
[[ 8.48528137 11.3137085   5.83095189]
 [ 5.65685425  8.48528137  3.16227766]
 [ 2.82842712  5.65685425  1.41421356]]
Матрица евклидовых расстояний без использования специальной функции:
[[ 8.48528137 11.3137085   5.83095189]
 [ 5.65685425  8.48528137  3.16227766]
 [ 2.82842712  5.65685425  1.41421356]]
функцией scipy.spatial.distance.cdist по скорости работы быстрее


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [9]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?2. 

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [10]:
crunchie_munchies_calories = 60
average_calories = np.mean(calorie_stats)-crunchie_munchies_calories
print(f'Среднее количество калорий у конкурентов выше на {average_calories}')

Среднее количество калорий у конкурентов выше на 46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [12]:
calorie_stats_sorted = np.sort(calorie_stats)
print('Отсортированные данные:')
print(calorie_stats_sorted)

Отсортированные данные:
[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [14]:
median_calories = np.median(calorie_stats)
print(f'Медиана в наборе данных {median_calories}')

 Медиана в наборе данных 110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [17]:
for p in range(0,101):
    percentile = np.percentile(calorie_stats, p)
    if percentile > 60:
        least_percentile = percentile
        break

print(f'Наименьший процентиль, превышающий 60 калорий {least_percentile}')



 Наименьший процентиль, превышающий 60 калорий 70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [19]:
condition = calorie_stats > 60
percent = sum(condition)/len(calorie_stats) * 100
print(f'Процент хлопьев, превышающих 60 калорий на порцию {percent}')

 Процент хлопьев, превышающих 60 калорий на порцию 96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [21]:
calorie_std = np.std(calorie_stats, ddof=1)
print(f'Стандартное отклонение равно {calorie_std}')

тандартное отклонение равно 19.484119056820845


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
Анализ результатов показывает, что подавляющее большинство марок хлопьев (96,1%) содержит более 60 граммов в одной порции. С одной стороны, увеличение количества хлопьев в порции способствует повышению содержания углеводов, клетчатки и других полезных веществ. Однако, с другой стороны, это также может приводить к повышению уровня глюкозы в крови за счёт содержания сахара и увеличению калорийности.

В связи с этим компания CrunchieMunchies может направить свои маркетинговые усилия на следующие сегменты потребителей, такие как:
a) те, кто уделяет внимание контролю уровня глюкозы в крови;
б) те, кто следит за калорийностью своего рациона.